"""League-name aliases for Dongqiudi ↔ Polymarket matching.

Keys are lowercase DQD short names, English labels, or PM `league_id` codes.
Values are short canonical codes. When both sides resolve to known codes, they
must be equal (fuzzy alone cannot separate 中甲 vs 中乙).
"""

from __future__ import annotations

# Display / id → canonical league code.
LEAGUE_ALIASES: dict[str, str] = {
    # --- China (PM: chi=CSL, chi2=League One; Chile is chi1/chl2) ---
    "中超": "cnsl",
    "csl": "cnsl",
    "chinese super league": "cnsl",
    "china super league": "cnsl",
    "chi": "cnsl",
    "中甲": "cnl1",
    "china league one": "cnl1",
    "china league 1": "cnl1",
    "chi2": "cnl1",
    "中乙": "cnl2",
    "china league two": "cnl2",
    "china league 2": "cnl2",
    # --- Chile ---
    "智甲": "cl1",
    "chile primera": "cl1",
    "chi1": "cl1",
    "智乙": "cl2",
    "chile segunda": "cl2",
    "chl2": "cl2",
    # --- Uruguay ---
    "乌拉甲": "uru1",
    "uruguay": "uru1",
    "uruguay primera": "uru1",
    "uru1": "uru1",
    # --- Common DQD shorts seen in bridge (PM league_id) ---
    "爱超": "irl1",
    "irl1": "irl1",
    "瑞士超": "sui",
    "sui": "sui",
    "斯伐超": "svk1",
    "svk1": "svk1",
    "保甲": "bul",
    "bul": "bul",
    "挪甲": "nor2",
    "nor2": "nor2",
    "挪超": "nor",
    "nor": "nor",
    "eliteserien": "nor",
    "丹超": "den",
    "den": "den",
    "斯亚甲": "slo",
    "slo": "slo",
    "罗甲": "rou1",
    "rou1": "rou1",
    "匈甲": "hun",
    "hun": "hun",
    "塞尔超": "srb",
    "srb": "srb",
    "阿乙": "argpn",
    "argpn": "argpn",
    "捷甲": "cze1",
    "cze1": "cze1",
    "秘鲁甲": "per1",
    "per1": "per1",
    "波兰超": "pol",
    "pol": "pol",
    "哥伦甲": "col1",
    "col1": "col1",
    "哥伦乙": "col2",
    "col2": "col2",
    "巴甲": "bra",
    "brasileirão": "bra",
    "brasileirao": "bra",
    "bra": "bra",
    "巴乙": "bra2",
    "bra2": "bra2",
    "美乙": "uslc",
    "uslc": "uslc",
    "美甲": "usl1",
    "usl1": "usl1",
    "哥斯甲": "fpd",
    "fpd": "fpd",
    "墨超": "mex",
    "liga mx": "mex",
    "mex": "mex",
    "厄瓜甲": "ecu1",
    "ecu1": "ecu1",
    "危地甲": "gtm",
    "gtm": "gtm",
    "瑞典超": "swe",
    "allsvenskan": "swe",
    "swe": "swe",
    "瑞典甲": "swe2",
    "swe2": "swe2",
    "芬超": "fin1",
    "fin1": "fin1",
    "哈萨克超": "kaz1",
    "kaz1": "kaz1",
    "立陶超": "ltu1",
    "ltu1": "ltu1",
    "拉脱超": "lva1",
    "lva1": "lva1",
    "冰岛超": "isl1",
    "isl1": "isl1",
    "k league 1": "kor",
    "k league": "kor",
    "kor": "kor",
    "韩K联": "kor",
    "K联赛": "kor",
    "k联赛": "kor",
    "奥地利杯": "atc",
    "atc": "atc",
    "巴丙": "bra3",
    "bra3": "bra3",
    "美女职": "nwsl",
    "nwsl": "nwsl",
    "苏联杯": "sclc",
    "scottish league cup": "sclc",
    "sclc": "sclc",
    "mls": "mls",
}
