"""League-name aliases for Dongqiudi ↔ Polymarket matching.

Keys are lowercase DQD short names, English labels, or PM `league_id` codes.
Values are short canonical codes. When both sides resolve to known codes, they
must be equal (fuzzy alone cannot separate 中甲 vs 中乙).
"""

from __future__ import annotations

# Display / id → canonical league code.
LEAGUE_ALIASES: dict[str, str] = {
    # --- China (PM: chi=CSL, chi2=League One; Chile is chi1/chl2) ---
    "中超": "cnsl",
    "csl": "cnsl",
    "chinese super league": "cnsl",
    "china super league": "cnsl",
    "chi": "cnsl",
    "中甲": "cnl1",
    "china league one": "cnl1",
    "china league 1": "cnl1",
    "chi2": "cnl1",
    "中乙": "cnl2",
    "china league two": "cnl2",
    "china league 2": "cnl2",
    # --- Chile ---
    "智甲": "cl1",
    "chile primera": "cl1",
    "chi1": "cl1",
    "智乙": "cl2",
    "chile segunda": "cl2",
    "chl2": "cl2",
    # --- Uruguay ---
    "乌拉甲": "uru1",
    "uruguay": "uru1",
    "uruguay primera": "uru1",
    "uru1": "uru1",
    # --- Common DQD shorts seen in bridge (PM league_id) ---
    "爱超": "irl1",
    "irl1": "irl1",
    "瑞士超": "sui",
    "sui": "sui",
    "斯伐超": "svk1",
    "svk1": "svk1",
    "保甲": "bul",
    "bul": "bul",
    "挪甲": "nor2",
    "nor2": "nor2",
    "挪超": "nor",
    "nor": "nor",
    "eliteserien": "nor",
    "丹超": "den",
    "den": "den",
    "斯亚甲": "slo",
    "slo": "slo",
    "罗甲": "rou1",
    "rou1": "rou1",
    "匈甲": "hun",
    "hun": "hun",
    "塞尔超": "srb",
    "srb": "srb",
    "阿乙": "argpn",
    "argpn": "argpn",
    "捷甲": "cze1",
    "cze1": "cze1",
    "秘鲁甲": "per1",
    "per1": "per1",
    "波兰超": "pol",
    "pol": "pol",
    "哥伦甲": "col1",
    "col1": "col1",
    "哥伦乙": "col2",
    "col2": "col2",
    "巴甲": "bra",
    "brasileirão": "bra",
    "brasileirao": "bra",
    "bra": "bra",
    "巴乙": "bra2",
    "bra2": "bra2",
    "美乙": "uslc",
    "uslc": "uslc",
    "美甲": "usl1",
    "usl1": "usl1",
    "哥斯甲": "fpd",
    "fpd": "fpd",
    "墨超": "mex",
    "liga mx": "mex",
    "mex": "mex",
    "厄瓜甲": "ecu1",
    "ecu1": "ecu1",
    "危地甲": "gtm",
    "gtm": "gtm",
    "瑞典超": "swe",
    "allsvenskan": "swe",
    "swe": "swe",
    "瑞典甲": "swe2",
    "swe2": "swe2",
    "芬超": "fin1",
    "fin1": "fin1",
    "哈萨克超": "kaz1",
    "kaz1": "kaz1",
    "立陶超": "ltu1",
    "ltu1": "ltu1",
    "拉脱超": "lva1",
    "lva1": "lva1",
    "冰岛超": "isl1",
    "isl1": "isl1",
    "k league 1": "kor",
    "k league": "kor",
    "kor": "kor",
    "韩K联": "kor",
    "K联赛": "kor",
    "k联赛": "kor",
    "奥地利杯": "atc",
    "atc": "atc",
    "巴丙": "bra3",
    "bra3": "bra3",
    "美女职": "nwsl",
    "nwsl": "nwsl",
    "苏联杯": "sclc",
    "scottish league cup": "sclc",
    "sclc": "sclc",
    "苏超": "scop",
    "scop": "scop",
    "scottish premiership": "scop",
    "mls": "mls",
    "美职联": "mls",
    "major league soccer": "mls",
    "奥超": "aut",
    "aut": "aut",
    "austrian bundesliga": "aut",
    "克联": "hr1",
    "hr1": "hr1",
    "hnl": "hr1",
    "croatian first league": "hr1",
    "玻甲": "bol1",
    "bol1": "bol1",
    "bolivia primera": "bol1",
    "南非超": "saf1",
    "saf1": "saf1",
    "south african premier": "saf1",
    # --- UEFA / club friendlies (PM codes dominate unmatched window) ---
    "欧冠": "ucl",
    "ucl": "ucl",
    "uefa champions league": "ucl",
    "champions league": "ucl",
    "欧联": "uel",
    "uel": "uel",
    "uefa europa league": "uel",
    "europa league": "uel",
    "欧协联": "col",
    "col": "col",
    "uefa europa conference league": "col",
    "uefa conference league": "col",
    "conference league": "col",
    "球会友谊": "clf",
    "clf": "clf",
    "club friendlies": "clf",
    "club friendly": "clf",
    "friendlies clubs": "clf",
    # --- South America / regional cups ---
    "南球杯": "sud",
    "sud": "sud",
    "sudamericana": "sud",
    "copa sudamericana": "sud",
    "巴西杯": "brco",
    "brco": "brco",
    "copa do brasil": "brco",
    "委内超": "ven1",
    "ven1": "ven1",
    "venezuela primera": "ven1",
    "liga futve": "ven1",
    "葡超杯": "ptsc",
    "ptsc": "ptsc",
    "portuguese super cup": "ptsc",
    "supertaça": "ptsc",
    "supertaca": "ptsc",
    "澳足总": "auc",
    "auc": "auc",
    "australia cup": "auc",
    "ffa cup": "auc",
    # --- Eastern Europe ---
    "乌克超": "ukr1",
    "ukr1": "ukr1",
    "ukraine premier league": "ukr1",
    "爱沙甲": "est1",
    "est1": "est1",
    "meistriliiga": "est1",
    # --- Leagues Cup / Faroe / UWCL (PM codes vs DQD shorts) ---
    "北美联杯": "lec",
    "lec": "lec",
    "leagues cup": "lec",
    "法罗超": "fro1",
    "fro1": "fro1",
    "faroe islands premier": "fro1",
    "女足欧冠": "uwcl",
    "uwcl": "uwcl",
    "uefa women champions league": "uwcl",
    "uwcl women": "uwcl",
    # --- ASEAN Championship (PM ASEAN ↔ DQD 东南锦) ---
    "东南锦": "asean",
    "asean": "asean",
    "asean championship": "asean",
    "aff": "asean",
    "aff championship": "asean",
    "aff suzuki cup": "asean",
    # --- NL / BE / PT / TR / GEO / cups (2026-08-09 PM↔DQD gaps) ---
    "荷甲": "ere",
    "ere": "ere",
    "eredivisie": "ere",
    "dutch eredivisie": "ere",
    "荷乙": "ned2",
    "ned2": "ned2",
    "eerste divisie": "ned2",
    "keuken kampioen divisie": "ned2",
    "keuken kampioen": "ned2",
    "比甲": "bel1",
    "bel1": "bel1",
    "jupiler pro league": "bel1",
    "belgian pro league": "bel1",
    "jupiler league": "bel1",
    "葡超": "por",
    "por": "por",
    "liga portugal": "por",
    "primeira liga": "por",
    "liga nos": "por",
    "土甲": "tur2",
    "tur2": "tur2",
    "tff 1 lig": "tur2",
    "tff 1. lig": "tur2",
    "turkish 1 lig": "tur2",
    "1 lig": "tur2",
    "格鲁甲": "geo1",
    "geo1": "geo1",
    "erovnuli liga": "geo1",
    "georgia erovnuli": "geo1",
    "意大利杯": "itc",
    "itc": "itc",
    "coppa italia": "itc",
    "italian cup": "itc",
    "希腊杯": "grc",
    "grc": "grc",
    "greek cup": "grc",
    "greece cup": "grc",
    # --- 2026-08-13 PM↔DQD gaps (FR2/BL2/SPL/LIB/… league_floor=0) ---
    "法乙": "fr2",
    "fr2": "fr2",
    "ligue 2": "fr2",
    "french ligue 2": "fr2",
    "德乙": "bl2",
    "bl2": "bl2",
    "2. bundesliga": "bl2",
    "2 bundesliga": "bl2",
    "bundesliga 2": "bl2",
    "沙特联": "spl",
    "spl": "spl",
    "saudi pro league": "spl",
    "saudi league": "spl",
    "解放者杯": "lib",
    "lib": "lib",
    "libertadores": "lib",
    "copa libertadores": "lib",
    "乌兹职联": "uzb1",
    "uzb1": "uzb1",
    "uzbekistan super league": "uzb1",
    "阿联酋联": "uae1",
    "uae1": "uae1",
    "uae pro league": "uae1",
    "arabian gulf league": "uae1",
    "比乙": "bel2",
    "bel2": "bel2",
    "challenger pro league": "bel2",
    "belgian challenger": "bel2",
    "日职联": "jap",
    "jap": "jap",
    "j1100": "jap",
    "j1": "jap",
    "j-league": "jap",
    "j league": "jap",
    "j.league": "jap",
    "阿塞超": "aze1",
    "aze1": "aze1",
    "azerbaijan premier": "aze1",
    "西乙": "es2",
    "es2": "es2",
    "la liga 2": "es2",
    "laliga 2": "es2",
    "segunda division": "es2",
    "segunda división": "es2",
    "土超": "tur",
    "tur": "tur",
    "super lig": "tur",
    "süper lig": "tur",
    "superlig": "tur",
    "turkish super lig": "tur",
    "英冠": "elc",
    "elc": "elc",
    "efl championship": "elc",
    "championship": "elc",
    "english championship": "elc",
    "加拿大联": "canpl",
    "canpl": "canpl",
    "canadian premier league": "canpl",
    "cpl": "canpl",
    "南美杯": "sud",
}
