"""Team-name aliases for Dongqiudi ↔ Polymarket fuzzy matching.

Maintain this table in the **match-bridge** skill. Keys are lowercase / Chinese
display forms (after light cleanup); values are canonical English tokens that
`normalize_team()` compares.

Add a row when a near-miss fails the match threshold because of abbreviations,
translations, or club-name variants (e.g. UCV ↔ Universidad Central…).
"""

from __future__ import annotations

# CN / alt spellings / abbreviations → English canonical tokens.
TEAM_ALIASES: dict[str, str] = {
    # --- K League / Allsvenskan (early bridge) ---
    "首尔": "seoul",
    "富川1995": "bucheon",
    "富川": "bucheon",
    "安养": "anyang",
    "光州": "gwangju",
    "哈马比": "hammarby",
    "代格福什": "degerfors",
    "埃尔夫斯堡": "elfsborg",
    "天狼星": "sirius",
    "哈尔姆斯塔德": "halmstad",
    "赫根": "hacken",
    "卡尔马": "kalmar",
    "马尔默": "malmo",
    "马尔莫": "malmo",
    "佐加顿斯": "djurgardens",
    "西班牙": "spain",
    "阿根廷": "argentina",
    "克卢日大学": "universitatea cluj",
    "康斯坦察灯塔": "farul",
    "克卢日": "universitatea cluj",
    "华盛顿精神": "washington spirit",
    "波士顿传奇": "boston legacy",
    "bucheon fc 1995": "bucheon",
    "bucheon 1995": "bucheon",
    "fc seoul": "seoul",
    "fc anyang": "anyang",
    "gwangju fc": "gwangju",
    "hammarby if": "hammarby",
    "degerfors if": "degerfors",
    "if elfsborg": "elfsborg",
    "ik sirius": "sirius",
    "halmstads bk": "halmstad",
    "bk hacken": "hacken",
    "malmo ff": "malmo",
    "kalmar ff": "kalmar",
    "orgryte is": "orgryte",
    "djurgardens if": "djurgardens",
    "fc universitatea cluj": "universitatea cluj",
    "fcv farul constanta": "farul",
    "boston legacy fc": "boston legacy",
    # --- Copa Sudamericana ---
    # DQD short name "UCV" vs PM "Universidad Central de Venezuela FC"
    "ucv": "universidad central venezuela",
    "universidad central venezuela": "universidad central venezuela",
    "universidad central de venezuela": "universidad central venezuela",
    "universidad central de venezuela fc": "universidad central venezuela",
    # --- Denmark / Finland / Switzerland / Hungary ---
    "sønderjyske fodbold": "sonderjyske",
    "sønderjyske": "sonderjyske",
    "sonderjyske": "sonderjyske",
    "sönderjyske": "sonderjyske",
    "tampereen ilves": "ilves",
    "ilves tampere": "ilves",
    "ilves": "ilves",
    "young boys bern": "young boys",
    "bsc young boys": "young boys",
    "young boys": "young boys",
    "wkw eto fc gyor": "gyori eto",
    "wkw eto gyor": "gyori eto",
    "győri eto": "gyori eto",
    "gyori eto": "gyori eto",
    "fc københavn": "copenhagen",
    "københavn": "copenhagen",
    "copenhagen": "copenhagen",
    "hjk helsinki": "hjk",
    "hjk": "hjk",
    "turun palloseura": "tps",
    "tps": "tps",
    # --- Kazakhstan / Norway ---
    "fc yelimai": "yelimay",
    "yelimai": "yelimay",
    "fk yelimay semey": "yelimay",
    "yelimay semey": "yelimay",
    "yelimay": "yelimay",
    "kaisar kyzylorda": "kaysar",
    "kaisar": "kaysar",
    "kaysar": "kaysar",
    "kfum-kameratene oslo": "kfum oslo",
    "kfum kameratene oslo": "kfum oslo",
    "kfum kobenhavn": "kfum oslo",
    "kfum oslo": "kfum oslo",
    "hamarkameratene": "hamkam",
    "hamkam": "hamkam",
    "stabaek if": "stabaek",
    "stabaek": "stabaek",
    "stabæk": "stabaek",
    "hoedd il": "hodd",
    "hoedd": "hodd",
    "hødd": "hodd",
    "hodd": "hodd",
    # --- Austria cup variants ---
    "sc sparkasse imst": "imst",
    "sparkasse imst": "imst",
    "sc imst": "imst",
    "imst": "imst",
    "tsv egger glas hartberg": "hartberg",
    "tsv hartberg": "hartberg",
    "hartberg": "hartberg",
    "spg wallern/marienkirchen": "wallern",
    "spg wallern marienkirchen": "wallern",
    "sv wallern": "wallern",
    "wallern": "wallern",
    "fc flyeralarm admira": "admira",
    "flyeralarm admira": "admira",
    "trenkwalder admira wacker": "admira",
    "admira wacker": "admira",
    "admira": "admira",
    "fk austria wien": "austria vienna",
    "austria wien": "austria vienna",
    "austria vienna": "austria vienna",
    # --- Brazil ---
    "cruzeiro ec": "cruzeiro",
    "cruzeiro esporte clube": "cruzeiro",
    "cruzeiro": "cruzeiro",
    "botafogo fr": "botafogo",
    "ypiranga fc rs": "ypiranga",
    "ypiranga rs": "ypiranga",
    "ypiranga erechim": "ypiranga",
    "ypiranga": "ypiranga",
    "ser caxias do sul": "caxias",
    "caxias": "caxias",
    "amazonas fc am": "amazonas",
    "amazonas am": "amazonas",
    "paysandu sc pa": "paysandu",
    "paysandu pa": "paysandu",
    "paysandu interior": "paysandu",
    "paysandu": "paysandu",
    "cr brasil": "crb",
    "crb": "crb",
    "aa internacional limeira sp": "inter limeira",
    "internacional limeira sp": "inter limeira",
    "inter de limeira": "inter limeira",
    "inter limeira": "inter limeira",
    "ituano fc sp": "ituano",
    "ituano sp": "ituano",
    # --- Colombia / NWSL / Latvia ---
    "internacional fc de palmira": "internacional palmira",
    "internacional palmira": "internacional palmira",
    "internacional f.c.": "internacional palmira",
    "internacional f c": "internacional palmira",
    "san diego wave fc": "san diego wave",
    "san diego wave (w)": "san diego wave",
    "san diego wave w": "san diego wave",
    "denver summit fc": "denver summit",
    "denver summit w": "denver summit",
    "angel city fc": "angel city",
    "angel city fc (w)": "angel city",
    "angel city w": "angel city",
    "racing louisville fc": "racing louisville",
    "racing louisville (w)": "racing louisville",
    "racing louisville w": "racing louisville",
    "fc rfs": "rfs",
    "rfs": "rfs",
    "rīgas fs": "rfs",
    "rigas fs": "rfs",
    "fk tukums 2000/tss": "tukums",
    "tukums 2000 tss": "tukums",
    "tukums": "tukums",
    # --- China CSL (PM Haigang / San Zhen vs DQD Port / Three Towns) ---
    "shanghai haigang": "shanghai port",
    "shanghai haigang fc": "shanghai port",
    "shanghai port": "shanghai port",
    "shanghai port fc": "shanghai port",
    "wuhan san zhen": "wuhan three towns",
    "wuhan san zhen fc": "wuhan three towns",
    "wuhan three towns": "wuhan three towns",
    "wuhan three towns fc": "wuhan three towns",
    # --- Scotland / Denmark / Finland ---
    "heart of midlothian": "hearts",
    "heart of midlothian fc": "hearts",
    "hearts": "hearts",
    "hearts fc": "hearts",
    "aarhus gf": "agf",
    "aarhus": "agf",
    "agf": "agf",
    "agf aarhus": "agf",
    "kuopion palloseura": "kups",
    "kups": "kups",
    "gnistan helsinki": "gnistan",
    "if gnistan": "gnistan",
    "gnistan": "gnistan",
    # --- Austria / Slovenia / Slovakia / Croatia / Romania ---
    "wsg swarovski tirol": "wsg tirol",
    "wsg tirol": "wsg tirol",
    "nk publikum celje": "celje",
    "publikum celje": "celje",
    "nk celje": "celje",
    "celje": "celje",
    "mura murska sobota": "ns mura",
    "nš mura": "ns mura",
    "ns mura": "ns mura",
    "nk mura": "ns mura",
    "nafta 1903 lendava": "nafta",
    "nafta 1903": "nafta",
    "nafta": "nafta",
    "fk zeleziarne podbrezova": "podbrezova",
    "zeleziarne podbrezova": "podbrezova",
    "sport podbrezova": "podbrezova",
    "podbrezova": "podbrezova",
    "istra 1961 pula": "istra 1961",
    "nk istra 1961": "istra 1961",
    "istra 1961": "istra 1961",
    "fc petrolul ploiesti": "petrolul",
    "petrolul ploiesti": "petrolul",
    "petrolul 52": "petrolul",
    "petrolul": "petrolul",
    # --- Colombia / Brazil cup ---
    "ad pasto": "deportivo pasto",
    "deportivo pasto": "deportivo pasto",
    "aguilas doradas rionegro": "rionegro",
    "aguilas doradas": "rionegro",
    "rionegro": "rionegro",
    "ad cali": "deportivo cali",
    "deportivo cali": "deportivo cali",
    "clube de regatas vasco da gama": "vasco",
    "clube regatas vasco da gama": "vasco",
    "cr vasco da gama": "vasco",
    "vasco da gama": "vasco",
    "vasco": "vasco",
    "fluminense rj": "fluminense",
    "fluminense fc": "fluminense",
    "fluminense": "fluminense",
}
