"""Team-name aliases for Dongqiudi ↔ Polymarket fuzzy matching.

Maintain this table in the **match-bridge** skill. Keys are lowercase / Chinese
display forms (after light cleanup); values are canonical English tokens that
`normalize_team()` compares.

Add a row when a near-miss fails the match threshold because of abbreviations,
translations, or club-name variants (e.g. UCV ↔ Universidad Central…).
"""

from __future__ import annotations

# CN / alt spellings / abbreviations → English canonical tokens.
TEAM_ALIASES: dict[str, str] = {
    # --- K League / Allsvenskan (early bridge) ---
    "首尔": "seoul",
    "富川1995": "bucheon",
    "富川": "bucheon",
    "安养": "anyang",
    "光州": "gwangju",
    "哈马比": "hammarby",
    "代格福什": "degerfors",
    "埃尔夫斯堡": "elfsborg",
    "天狼星": "sirius",
    "哈尔姆斯塔德": "halmstad",
    "赫根": "hacken",
    "卡尔马": "kalmar",
    "马尔默": "malmo",
    "马尔莫": "malmo",
    "佐加顿斯": "djurgardens",
    "西班牙": "spain",
    "阿根廷": "argentina",
    "克卢日大学": "universitatea cluj",
    "康斯坦察灯塔": "farul",
    "克卢日": "universitatea cluj",
    "华盛顿精神": "washington spirit",
    "波士顿传奇": "boston legacy",
    "bucheon fc 1995": "bucheon",
    "bucheon 1995": "bucheon",
    "fc seoul": "seoul",
    "fc anyang": "anyang",
    "gwangju fc": "gwangju",
    "hammarby if": "hammarby",
    "degerfors if": "degerfors",
    "if elfsborg": "elfsborg",
    "ik sirius": "sirius",
    "halmstads bk": "halmstad",
    "bk hacken": "hacken",
    "malmo ff": "malmo",
    "kalmar ff": "kalmar",
    "orgryte is": "orgryte",
    "djurgardens if": "djurgardens",
    "fc universitatea cluj": "universitatea cluj",
    "fcv farul constanta": "farul",
    "boston legacy fc": "boston legacy",
    # --- Copa Sudamericana ---
    # DQD short name "UCV" vs PM "Universidad Central de Venezuela FC"
    "ucv": "universidad central venezuela",
    "universidad central venezuela": "universidad central venezuela",
    "universidad central de venezuela": "universidad central venezuela",
    "universidad central de venezuela fc": "universidad central venezuela",
    # --- Denmark / Finland / Switzerland / Hungary ---
    "sønderjyske fodbold": "sonderjyske",
    "sønderjyske": "sonderjyske",
    "sonderjyske": "sonderjyske",
    "sönderjyske": "sonderjyske",
    "tampereen ilves": "ilves",
    "ilves tampere": "ilves",
    "ilves": "ilves",
    "young boys bern": "young boys",
    "bsc young boys": "young boys",
    "young boys": "young boys",
    "wkw eto fc gyor": "gyori eto",
    "wkw eto gyor": "gyori eto",
    "győri eto": "gyori eto",
    "gyori eto": "gyori eto",
    "fc københavn": "copenhagen",
    "københavn": "copenhagen",
    "copenhagen": "copenhagen",
    "hjk helsinki": "hjk",
    "hjk": "hjk",
    "turun palloseura": "tps",
    "tps": "tps",
    # --- Kazakhstan / Norway ---
    "fc yelimai": "yelimay",
    "yelimai": "yelimay",
    "fk yelimay semey": "yelimay",
    "yelimay semey": "yelimay",
    "yelimay": "yelimay",
    "kaisar kyzylorda": "kaysar",
    "kaisar": "kaysar",
    "kaysar": "kaysar",
    "kfum-kameratene oslo": "kfum oslo",
    "kfum kameratene oslo": "kfum oslo",
    "kfum kobenhavn": "kfum oslo",
    "kfum oslo": "kfum oslo",
    "hamarkameratene": "hamkam",
    "hamkam": "hamkam",
    "stabaek if": "stabaek",
    "stabaek": "stabaek",
    "stabæk": "stabaek",
    "hoedd il": "hodd",
    "hoedd": "hodd",
    "hødd": "hodd",
    "hodd": "hodd",
    # --- Austria cup variants ---
    "sc sparkasse imst": "imst",
    "sparkasse imst": "imst",
    "sc imst": "imst",
    "imst": "imst",
    "tsv egger glas hartberg": "hartberg",
    "tsv hartberg": "hartberg",
    "hartberg": "hartberg",
    "spg wallern/marienkirchen": "wallern",
    "spg wallern marienkirchen": "wallern",
    "sv wallern": "wallern",
    "wallern": "wallern",
    "fc flyeralarm admira": "admira",
    "flyeralarm admira": "admira",
    "trenkwalder admira wacker": "admira",
    "admira wacker": "admira",
    "admira": "admira",
    "fk austria wien": "austria vienna",
    "austria wien": "austria vienna",
    "austria vienna": "austria vienna",
    # --- Brazil ---
    "cruzeiro ec": "cruzeiro",
    "cruzeiro esporte clube": "cruzeiro",
    "cruzeiro": "cruzeiro",
    "botafogo fr": "botafogo",
    "ypiranga fc rs": "ypiranga",
    "ypiranga rs": "ypiranga",
    "ypiranga erechim": "ypiranga",
    "ypiranga": "ypiranga",
    "ser caxias do sul": "caxias",
    "caxias": "caxias",
    "amazonas fc am": "amazonas",
    "amazonas am": "amazonas",
    "paysandu sc pa": "paysandu",
    "paysandu pa": "paysandu",
    "paysandu interior": "paysandu",
    "paysandu": "paysandu",
    "cr brasil": "crb",
    "crb": "crb",
    "aa internacional limeira sp": "inter limeira",
    "internacional limeira sp": "inter limeira",
    "inter de limeira": "inter limeira",
    "inter limeira": "inter limeira",
    "ituano fc sp": "ituano",
    "ituano sp": "ituano",
    # --- Colombia / NWSL / Latvia ---
    "internacional fc de palmira": "internacional palmira",
    "internacional palmira": "internacional palmira",
    "internacional f.c.": "internacional palmira",
    "internacional f c": "internacional palmira",
    "san diego wave fc": "san diego wave",
    "san diego wave (w)": "san diego wave",
    "san diego wave w": "san diego wave",
    "denver summit fc": "denver summit",
    "denver summit w": "denver summit",
    "angel city fc": "angel city",
    "angel city fc (w)": "angel city",
    "angel city w": "angel city",
    "racing louisville fc": "racing louisville",
    "racing louisville (w)": "racing louisville",
    "racing louisville w": "racing louisville",
    "fc rfs": "rfs",
    "rfs": "rfs",
    "rīgas fs": "rfs",
    "rigas fs": "rfs",
    "fk tukums 2000/tss": "tukums",
    "tukums 2000 tss": "tukums",
    "tukums": "tukums",
    # --- China CSL (PM Haigang / San Zhen vs DQD Port / Three Towns) ---
    "shanghai haigang": "shanghai port",
    "shanghai haigang fc": "shanghai port",
    "shanghai port": "shanghai port",
    "shanghai port fc": "shanghai port",
    "wuhan san zhen": "wuhan three towns",
    "wuhan san zhen fc": "wuhan three towns",
    "wuhan three towns": "wuhan three towns",
    "wuhan three towns fc": "wuhan three towns",
    # --- Scotland / Denmark / Finland ---
    "heart of midlothian": "hearts",
    "heart of midlothian fc": "hearts",
    "hearts": "hearts",
    "hearts fc": "hearts",
    "aarhus gf": "agf",
    "aarhus": "agf",
    "agf": "agf",
    "agf aarhus": "agf",
    "kuopion palloseura": "kups",
    "kuopion ps": "kups",
    "kups": "kups",
    "gnistan helsinki": "gnistan",
    "if gnistan": "gnistan",
    "gnistan": "gnistan",
    # --- UEL / UECL name shorts ---
    "kf vikingur": "vikingur reykjavik",
    "vikingur reykjavik": "vikingur reykjavik",
    "vikingur r": "vikingur reykjavik",
    "rigas futbola skola": "rfs",
    "fk rigas futbola skola": "rfs",
    "shkendija tetovo": "shkendija",
    "shkendija 79": "shkendija",
    "kf shkendija 79": "shkendija",
    "kf shkendija": "shkendija",
    "shkendija": "shkendija",
    "shkendija tetove": "shkendija",
    "kf shkenija 79": "shkendija",
    # --- Austria / Slovenia / Slovakia / Croatia / Romania ---
    "wsg swarovski tirol": "wsg tirol",
    "wsg tirol": "wsg tirol",
    "nk publikum celje": "celje",
    "publikum celje": "celje",
    "nk celje": "celje",
    "celje": "celje",
    "mura murska sobota": "ns mura",
    "nš mura": "ns mura",
    "ns mura": "ns mura",
    "nk mura": "ns mura",
    "nafta 1903 lendava": "nafta",
    "nafta 1903": "nafta",
    "nafta": "nafta",
    "fk zeleziarne podbrezova": "podbrezova",
    "zeleziarne podbrezova": "podbrezova",
    "sport podbrezova": "podbrezova",
    "podbrezova": "podbrezova",
    "istra 1961 pula": "istra 1961",
    "nk istra 1961": "istra 1961",
    "istra 1961": "istra 1961",
    "fc petrolul ploiesti": "petrolul",
    "petrolul ploiesti": "petrolul",
    "petrolul 52": "petrolul",
    "petrolul": "petrolul",
    # --- Colombia / Brazil cup ---
    "ad pasto": "deportivo pasto",
    "deportivo pasto": "deportivo pasto",
    "aguilas doradas rionegro": "rionegro",
    "aguilas doradas": "rionegro",
    "rionegro": "rionegro",
    "ad cali": "deportivo cali",
    "deportivo cali": "deportivo cali",
    "clube de regatas vasco da gama": "vasco",
    "clube regatas vasco da gama": "vasco",
    "cr vasco da gama": "vasco",
    "vasco da gama": "vasco",
    "vasco": "vasco",
    "fluminense rj": "fluminense",
    "fluminense fc": "fluminense",
    "fluminense": "fluminense",
    # --- Denmark / Finland short names (OB, SJK) ---
    "odense bk": "odense",
    "odense": "odense",
    "ob": "odense",
    "ob odense": "odense",
    "seinajoen jk": "sjk",
    "seinajoki": "sjk",
    "sjk seinajoki": "sjk",
    "sjk seinajoen": "sjk",
    "sjk": "sjk",
    # --- Ecuador LDU ---
    "ldu quito": "ldu quito",
    "ldu": "ldu quito",
    "liga dep universitaria quito": "ldu quito",
    "liga deportiva universitaria quito": "ldu quito",
    "liga universitaria quito": "ldu quito",
    # --- Kazakhstan Kairat (PM Qairat transliteration) ---
    "qairat": "kairat",
    "qairat fk": "kairat",
    "fc kairat almaty": "kairat",
    "kairat almaty": "kairat",
    "kairat fk": "kairat",
    "kairat": "kairat",
    "pfk levski sofia": "levski sofia",
    "levski sofia": "levski sofia",
    "levski": "levski sofia",
    # --- Faroe Islands ---
    "hb torshavn": "hb torshavn",
    "hb torshavn fo": "hb torshavn",
    "havnar boltfelag": "hb torshavn",
    "hb": "hb torshavn",
    "nsi runavik": "nsi",
    "nsí runavik": "nsi",
    "nsi": "nsi",
    "nsí": "nsi",
    # --- UWCL / Iceland women ---
    "umf breiðablik": "breidablik",
    "umf breidablik": "breidablik",
    "breidablik": "breidablik",
    "aqtöbe fk": "aktobe",
    "aqtobe fk": "aktobe",
    "aqtobe": "aktobe",
    "aktobe w": "aktobe",
    "aktobe fk": "aktobe",
    "aktobe": "aktobe",
    # --- Leagues Cup (MLS / Liga MX short forms) ---
    "columbus crew": "columbus",
    "columbus sc": "columbus",
    "columbus": "columbus",
    "atlas fc": "atlas",
    "atlas guadalajara": "atlas",
    "atlas": "atlas",
    "pumas de la unam": "pumas unam",
    "pumas u.n.a.m.": "pumas unam",
    "pumas u n a m": "pumas unam",
    "pumas unam": "pumas unam",
    "club universidad nacional": "pumas unam",
    "tigres de la uanl": "tigres uanl",
    "tigres uanl": "tigres uanl",
    "cf tigres uanl": "tigres uanl",
    "vancouver whitecaps fc": "vancouver whitecaps",
    "vancouver whitecaps": "vancouver whitecaps",
    "atlante fc": "atlante",
    "cf atlante": "atlante",
    "atlante": "atlante",
    "fc cincinnati": "cincinnati",
    "cincinnati": "cincinnati",
    "cf pachuca": "pachuca",
    "pachuca": "pachuca",
    "charlotte fc": "charlotte",
    "charlotte": "charlotte",
    "real salt lake": "real salt lake",
    # --- Serie A / friendlies ---
    "inter milano": "internazionale",
    "inter milan": "internazionale",
    "internazionale": "internazionale",
    "ac milan": "milan",
    "milan": "milan",
    "sassuolo calcio": "sassuolo",
    "us sassuolo": "sassuolo",
    "sassuolo": "sassuolo",
    "rc celta de vigo": "celta",
    "celta de vigo": "celta",
    "rc celta": "celta",
    "celta": "celta",
    # --- ASEAN / Bolivia / Colombia ---
    "gv cd san jose": "gv san jose",
    "gualberto villarroel deportivo san jose": "gv san jose",
    "gualberto villarroel": "gv san jose",
    "gualberto villarroel sj": "gv san jose",
    "gualberto villarroel san jose": "gv san jose",
    "cd san antonio bulo bulo": "san antonio bulo bulo",
    "san antonio bulo bulo": "san antonio bulo bulo",
    "cd la equidad seguros": "la equidad",
    "la equidad": "la equidad",
    "la equidad seguros": "la equidad",
    "internacional de bogota": "la equidad",
    "jaguares de cordoba fc": "jaguares cordoba",
    "jaguares de cordoba": "jaguares cordoba",
    "jaguares cordoba": "jaguares cordoba",
    # --- UWCL (PM long forms ↔ DQD women shorts ↔ AF "… W") ---
    "juventus women": "juventus",
    "sc uniao torreense": "torreense",
    "scu torreense w": "torreense",
    "scu torreense": "torreense",
    "torreense w": "torreense",
    "torreense": "torreense",
    "eintracht frankfurt women": "eintracht frankfurt",
    "as omonoia leukosias": "omonia",
    "omonia nicosia": "omonia",
    "omonia": "omonia",
    "skn st polten frauen": "st polten",
    "st polten": "st polten",
    "bsc young boys frauen": "young boys",
    "young boys women": "young boys",
    "young boys": "young boys",
    "fc gintra universitetas": "gintra",
    "gintra universitetas": "gintra",
    "gintra": "gintra",
    "heart of midlothian lfc": "hearts",
    "hearts w": "hearts",
    "hearts": "hearts",
    "zhfk sisters": "seasters",
    "seasters odessa women": "seasters",
    "seasters odessa": "seasters",
    "seasters": "seasters",
    "oud heverlee leuven women": "oh leuven",
    "oud heverlee leuven": "oh leuven",
    "oh leuven w": "oh leuven",
    "oh leuven": "oh leuven",
    "fk tsc backa topola": "backa topola",
    "tsc backa topola": "backa topola",
    "backa topola w": "backa topola",
    "tsc w": "backa topola",
    "backa topola": "backa topola",
    "zhfk metalist 1925 kharkiv": "zhytlobud",
    "metalist 1925 kharkiv": "zhytlobud",
    "metalist 1925 w": "zhytlobud",
    "metalist 1925": "zhytlobud",
    "zhytlobud 1": "zhytlobud",
    "zhytlobud": "zhytlobud",
    "fenerbahce sk w": "fenerbahce",
    "fenerbahce sk": "fenerbahce",
    "fenerbahce w": "fenerbahce",
    "fenerbahce": "fenerbahce",
    "racing fc union letzebuerg": "racing luxembourg",
    "racing fc union luxembourg": "racing luxembourg",
    "racing w": "racing luxembourg",
    "racing luxembourg w": "racing luxembourg",
    "racing luxembourg": "racing luxembourg",
    "helsingin jk": "hjk",
    "hjk w": "hjk",
    "hjk": "hjk",
    "ajax amsterdam women": "ajax",
    "ajax w": "ajax",
    "afc ajax": "ajax",
    "ajax": "ajax",
    "brondby w": "brondby",
    "brondby if": "brondby",
    "brondby": "brondby",
    "sporting cp": "sporting cp",
    # --- 2026-08-09 PM↔DQD side-name gaps ---
    # Belgium
    "royal charleroi": "charleroi",
    "royal charleroi sc": "charleroi",
    "sporting charleroi": "charleroi",
    "rc sporting charleroi": "charleroi",
    "charleroi": "charleroi",
    # Slovenia
    "nk aluminij": "aluminij",
    "aluminij kidricevo": "aluminij",
    "aluminij": "aluminij",
    "nk bravo": "bravo",
    "bravo ljubljana": "bravo",
    "bravo": "bravo",
    # Croatia (Varteks rebrand)
    "nk varteks varazdin": "varazdin",
    "varteks varazdin": "varazdin",
    "nk varazdin": "varazdin",
    "nk varaždin": "varazdin",
    "varazdin": "varazdin",
    # Brazil Série B
    "atletico go": "atletico goianiense",
    "atlético go": "atletico goianiense",
    "ac goianiense": "atletico goianiense",
    "goianiense": "atletico goianiense",
    "atletico goianiense": "atletico goianiense",
    "atlético goianiense": "atletico goianiense",
    # Romania
    "cs hunedoara": "hunedoara",
    "corvinul 1921 hunedoara": "hunedoara",
    "fc corvinul 1921 hunedoara": "hunedoara",
    "corvinul hunedoara": "hunedoara",
    "hunedoara": "hunedoara",
    # Netherlands reserves / Jong
    "jong az alkmaar": "az ii",
    "jong az": "az ii",
    "az ii": "az ii",
    "az 2": "az ii",
    "jong psv eindhoven": "psv ii",
    "jong psv": "psv ii",
    "psv ii": "psv ii",
    "psv 2": "psv ii",
    "jong utrecht": "utrecht ii",
    "jong fc utrecht": "utrecht ii",
    "utrecht ii": "utrecht ii",
    "utrecht 2": "utrecht ii",
    # Greece cup spelling
    "ae larisas 1964": "larissa",
    "larisas 1964": "larissa",
    "larisas": "larissa",
    "ae larissa": "larissa",
    "larissa": "larissa",
}
